
seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001 
model:
  class_path: SwinUnetTempLightning
  init_args:
    n_channels: 7
    flatten_temporal_dimension: false
    pos_class_weight: 236
    loss_function: Dice
    crop_before_eval: true

do_train: true
do_test: true
do_predict: false
