# pytorch_lightning==2.0.1
# Need to find best parameters 
seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
model:
  class_path: TSViTLightning
  init_args:
    n_channels: 5
    flatten_temporal_dimension: false
    pos_class_weight: 10
    loss_function: "BCE"
    img_res: 128
    patch_size: 8
    max_seq_len: 5
    dim: 512
    temporal_depth: 2
    spatial_depth: 2
    heads: 4
    dim_head: 32
    dropout: 0.
    emb_dropout: 0.
    scale_dim: 4
do_train: true
do_test: true
do_predict: false
