seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
model:
  class_path: TSViTLightningSeb
  init_args:
    n_channels: 5
    flatten_temporal_dimension: false
    pos_class_weight: 16
    loss_function: "BCE"
    img_size: [128, 128]
do_train: true